/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastro01_06;

import javax.swing.JOptionPane;

/**
 *
 * @author dti
 */
public class Teste extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public Teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        rotulo1 = new javax.swing.JLabel();
        rotulo2 = new javax.swing.JLabel();
        rotulo3 = new javax.swing.JLabel();
        rotulo4 = new javax.swing.JLabel();
        rotulo5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        texto1 = new javax.swing.JTextField();
        texto2 = new javax.swing.JTextField();
        lista = new javax.swing.JComboBox<>();
        texto5 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        texto3 = new javax.swing.JTextField();
        rotulo6 = new javax.swing.JLabel();
        texto4 = new javax.swing.JTextField();
        rotulo7 = new javax.swing.JLabel();
        texto6 = new javax.swing.JFormattedTextField();
        rotulo8 = new javax.swing.JLabel();
        texto7 = new javax.swing.JFormattedTextField();
        rotulo9 = new javax.swing.JLabel();
        texto8 = new javax.swing.JFormattedTextField();
        rotulo10 = new javax.swing.JLabel();
        texto9 = new javax.swing.JFormattedTextField();
        rotulo11 = new javax.swing.JLabel();
        texto10 = new javax.swing.JRadioButton();
        texto11 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titulo.setText("Cadastro de Clientes");
        titulo.setToolTipText("");

        rotulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo1.setText("Pesquisar:");

        rotulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo2.setText("ID:");

        rotulo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo3.setText("Nome/Empresa:");

        rotulo4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo4.setText("Município:");

        rotulo5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo5.setText("CEP:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        texto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        texto1.setEnabled(false);
        texto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto1ActionPerformed(evt);
            }
        });

        texto2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vinicius Valero Chabariberi", "Victor Navarro", "Pedro Fernandes de Araujo", "Nickolas Maia Araujo", "Leticia Borges da Silva" }));
        lista.setToolTipText("Profissionais");
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        try {
            texto5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        texto3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        rotulo6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo6.setText("Endereço:");

        texto4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        rotulo7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo7.setText("Tel:");

        try {
            texto6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        rotulo8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo8.setText("Cel:");

        try {
            texto7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        rotulo9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo9.setText("Cpf:");

        try {
            texto8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        texto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto8ActionPerformed(evt);
            }
        });

        rotulo10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo10.setText("Cnpj:");

        try {
            texto9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        texto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto9ActionPerformed(evt);
            }
        });

        rotulo11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rotulo11.setText("Gênero:");

        texto10.setText("M");
        texto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto10ActionPerformed(evt);
            }
        });

        texto11.setText("F");
        texto11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto11ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Pesquisar");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotulo1)
                            .addComponent(rotulo2)
                            .addComponent(rotulo3)
                            .addComponent(rotulo4)
                            .addComponent(rotulo6)
                            .addComponent(rotulo7)
                            .addComponent(rotulo5)
                            .addComponent(rotulo8)
                            .addComponent(rotulo9)
                            .addComponent(rotulo10)
                            .addComponent(rotulo11))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto10)
                                .addGap(62, 62, 62)
                                .addComponent(texto11))
                            .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lista, javax.swing.GroupLayout.Alignment.LEADING, 0, 290, Short.MAX_VALUE)
                                    .addComponent(texto2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(texto9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(texto8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(texto7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(texto6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(texto5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(texto4, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(131, 131, 131)
                        .addComponent(jButton2)))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo1)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo2)
                    .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo3)
                    .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo6)
                    .addComponent(texto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo4)
                    .addComponent(texto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo5)
                    .addComponent(texto5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo7)
                    .addComponent(texto6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rotulo8)
                    .addComponent(texto7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(texto8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotulo9))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rotulo10)
                    .addComponent(texto9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotulo11)
                    .addComponent(texto10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(56, 56, 56))
        );

        setBounds(0, 0, 820, 818);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nome, endereco, municipio, Profissionais, CEP, id, Tel, Cel, Cpf, Cnpj, escolha = " ";
            Profissionais = lista.getSelectedItem().toString();
            id = texto1.getText();
            nome = texto2.getText();
            endereco = texto3.getText();
            municipio = texto4.getText();
            CEP = texto5.getText();
            Tel = texto6.getText();
            Cel = texto7.getText();
            Cpf = texto8.getText();
            Cnpj = texto9.getText();
            
            if(texto10.isSelected()){
                escolha = texto10.getText();
            }
            
            if(texto11.isSelected()){
                escolha = texto11.getText();
            }
            
            JOptionPane.showMessageDialog(null, "Profissional: " + Profissionais + "\nid: " + id + "\nNome/Empresa: " + nome + "\nEndereço: " + endereco + "\nMunicípio: " + municipio + "\nCep: " + CEP + "\nTelefone: " + Tel + "\nCelular: " + Cel + "\nCPF: " + Cpf + "\nCnpj: " + Cnpj + "\nGenêro: " + escolha);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        texto1.setText(null);
        texto2.setText(null);
        texto3.setText(null);
        texto4.setText(null);
        texto5.setText(null);
        texto6.setText(null);
        texto7.setText(null);
        texto8.setText(null);
        texto9.setText(null);
        texto10.setText(null);
        texto11.setText(null);
        texto1.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaActionPerformed

    private void texto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto8ActionPerformed

    private void texto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto9ActionPerformed

    private void texto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto10ActionPerformed

    private void texto11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void texto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JLabel rotulo1;
    private javax.swing.JLabel rotulo10;
    private javax.swing.JLabel rotulo11;
    private javax.swing.JLabel rotulo2;
    private javax.swing.JLabel rotulo3;
    private javax.swing.JLabel rotulo4;
    private javax.swing.JLabel rotulo5;
    private javax.swing.JLabel rotulo6;
    private javax.swing.JLabel rotulo7;
    private javax.swing.JLabel rotulo8;
    private javax.swing.JLabel rotulo9;
    private javax.swing.JTextField texto1;
    private javax.swing.JRadioButton texto10;
    private javax.swing.JRadioButton texto11;
    private javax.swing.JTextField texto2;
    private javax.swing.JTextField texto3;
    private javax.swing.JTextField texto4;
    private javax.swing.JFormattedTextField texto5;
    private javax.swing.JFormattedTextField texto6;
    private javax.swing.JFormattedTextField texto7;
    private javax.swing.JFormattedTextField texto8;
    private javax.swing.JFormattedTextField texto9;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
