/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package combocheckboxjradiobutton;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author dti
 */
public class Teste extends javax.swing.JPanel {
    Integer tamfonte, estilo;
    /**
     * Creates new form Teste
     */
    public Teste() {
        initComponents();
                lista.addActionListener(
                new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
        if(lista.getSelectedItem().toString() == "Sem Cor")
            texto.setForeground(Color.black);                         
        if(lista.getSelectedItem().toString() == "Vermelho")
            texto.setForeground(Color.red);
        
        if(lista.getSelectedItem().toString() == "Azul")
            texto.setForeground(Color.blue);
        
        if(lista.getSelectedItem().toString() == "Verde")
            texto.setForeground(Color.green);
        
        if(lista.getSelectedItem().toString() == "Amarelo")
            texto.setForeground(Color.yellow);
        
        if(lista.getSelectedItem().toString() == "Branco")
            texto.setForeground(Color.white);
        
        if(lista.getSelectedItem().toString() == "Preto")
            texto.setForeground(Color.black);}});
        
        tam1.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent e){
               tamfonte=12;
               texto.setFont(new Font("",estilo,tamfonte));}});
        
        tam2.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent e){
               tamfonte=14;
               texto.setFont(new Font("",estilo,tamfonte));}});
        
        tam3.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent e){
               tamfonte=16;
               texto.setFont(new Font("",estilo,tamfonte));}});
        
        tam4.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent e){
               tamfonte=18;
               texto.setFont(new Font("",estilo,tamfonte));}});
        
        negrito.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                estilo=Font.BOLD;
                normal.setSelected(false);
                italico.setSelected(false);
                negritoitalico.setSelected(false);
                texto.setFont(new Font("",estilo,tamfonte));}});
        
        italico.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                estilo=Font.ITALIC;
                normal.setSelected(false);
                negrito.setSelected(false);
                negritoitalico.setSelected(false);
                texto.setFont(new Font("",estilo,tamfonte));}});
        
        normal.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                estilo=Font.PLAIN;
                negrito.setSelected(false);
                italico.setSelected(false);
                negritoitalico.setSelected(false);
                texto.setFont(new Font("",estilo,tamfonte));}});
        
        negritoitalico.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                estilo=Font.BOLD+Font.ITALIC;
                normal.setSelected(false);
                italico.setSelected(false);
                negrito.setSelected(false);
                texto.setFont(new Font("",estilo,tamfonte));}});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        negrito = new javax.swing.JCheckBox();
        normal = new javax.swing.JCheckBox();
        italico = new javax.swing.JCheckBox();
        negritoitalico = new javax.swing.JCheckBox();
        lista = new javax.swing.JComboBox<>();
        tam1 = new javax.swing.JRadioButton();
        tam2 = new javax.swing.JRadioButton();
        tam4 = new javax.swing.JRadioButton();
        tam3 = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tamanho");

        texto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        texto.setText("Programa feito em Java");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Estilo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Cor");

        negrito.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        negrito.setText("Negrito");
        negrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negritoActionPerformed(evt);
            }
        });

        normal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        normal.setText("Normal");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });

        italico.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        italico.setText("Itálico");

        negritoitalico.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        negritoitalico.setText("Negrito Itálico");
        negritoitalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negritoitalicoActionPerformed(evt);
            }
        });

        lista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem Cor", "Vermelho", "Azul", "Verde", "Amarelo", "Branco", "Preto", " " }));
        lista.setToolTipText("");
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        tam1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tam1.setText("12");

        tam2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tam2.setText("14");

        tam4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tam4.setText("18");

        tam3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tam3.setText("16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(italico)
                            .addComponent(negrito)
                            .addComponent(normal)
                            .addComponent(negritoitalico)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tam3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tam4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tam1)
                                        .addGap(42, 42, 42)
                                        .addComponent(tam2)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(negrito)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(italico)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(normal)
                        .addGap(18, 18, 18)
                        .addComponent(negritoitalico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tam1)
                    .addComponent(tam2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tam4)
                    .addComponent(tam3))
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void negritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negritoActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalActionPerformed

    private void negritoitalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritoitalicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negritoitalicoActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_listaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox italico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JCheckBox negrito;
    private javax.swing.JCheckBox negritoitalico;
    private javax.swing.JCheckBox normal;
    private javax.swing.JRadioButton tam1;
    private javax.swing.JRadioButton tam2;
    private javax.swing.JRadioButton tam3;
    private javax.swing.JRadioButton tam4;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables

    private void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
